#pragma once

// È­¸é 
const int Width = 800;
const int Height = 800;
// °´Ã¼ °¹¼ö
const int MAX_OBJ_COUNT{ 100 };
const int MAX_ARROW_COUNT{ 100 };

// ¸¶¿ì½º Å¬¸¯ ÄðÅ¸ÀÓ
const float COOLTIME{ 1.f };

enum OBJTYPE
{
	OBJECT_KING,
	OBJECT_BUILDING,
	OBJECT_GROUNDUNIT,
	OBJECT_BULLET,
	OBJECT_ARROW,
	OBJECT_FLYUNIT,
	OBJECT_BOMBUNIT
};

enum TEAM
{
	TEAM_MY,
	TEAM_YOUR
};

#define OBJLEVEL_FLY 0.05f
#define OBJLEVEL_BUILDING 0.1f
#define OBJLEVEL_CHARACTER 0.2f
#define OBJLEVEL_BOMB 0.25f
#define OBJLEVEL_BULLET 0.3f
#define OBJLEVEL_ARROW 0.3f
#define OBJLEVEL_BACKGROUND 0.99f

// Texture
enum TEXTURE
{
	TEX_BACKGROUND,
	TEX_KING1,
	TEX_KING2,
	TEX_BUILDING1,
	TEX_BUILDING2,
	TEX_GROUNDUNIT1,
	TEX_GROUNDUNIT2,
	TEX_FLYUNIT1,
	TEX_FLYUNIT2,
	TEX_BOMBUNIT1,
	TEX_BOMBUNIT2,
	TEX_BULLET1,
	TEX_BULLET2,
	TEX_FLYARROW1,
	TEX_FLYARROW2,
	TEX_WEATHER,
	TEX_MAX_COUNT,
};